name: biomovil
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  http: ^1.1.0
  json_serializable: ^6.7.1
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.0.0
  flutter_polyline_points: ^2.0.0
  location: ^5.0.3
  audioplayers: ^5.1.0
  qrscan: ^0.3.3
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.1
  flutter_markdown: ^0.6.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/locations.json
    - assets/galeria/
    - assets/animales/tropical/
    - assets/animales/sabana/
    - assets/animales/desierto/
